name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm install -g pkg
      - run: pkg --out-path . .
      - run: ls
      - run: rm -r node_modules
      - name: Upload Linux
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: vman-linux
          # Destination path
          path: .
      - name: Upload Windows
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: vman-windows.exe
          # Destination path
          path: .
      - name: Upload OS X
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: vman-macos
          # Destination path
          path: .

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@circutrider21'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
